spring:
  profiles: default 
  cloud:
    config:
      override-none: true
      server:
        git:
          uri: https://github.com/saiyedzaidi/microservices-config.git
          username: microservicesreadonly
          password: password1
server:
  port: 8888
  
management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'INFO'

---
spring:
  profiles: sapecloud
  cloud:
    config:
      server:
        git:
          uri: https://github.com/saiyedzaidi/microservices-config.git
          basedir: profiles/sapecloud
          username: microservicesreadonly
          password: password1
          

